[package]
name = "quote_server"
version = "0.1.0"
edition.workspace = true

[dependencies]
quote_common = { path = "../quote_common" }
crossbeam = { workspace = true }
rand = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
