[package]
name = "quote_client"
version = "0.1.0"
edition.workspace = true

[dependencies]
quote_common = { path = "../quote_common" }
clap = { workspace = true }
ctrlc = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
serde_json = { workspace = true }
